# S1/S2: weight degeneracy diagnostics, and a noise band from the real resampler
#
# Normalising the importance weights on the log scale stops them overflowing.
# It says nothing about whether they are informative: a run in which one
# candidate carries almost all the weight normalises perfectly well and reports
# nothing unusual, while the retained sample is effectively a handful of points.
# These are the numbers that expose that.

test_that("weight diagnostics are exact for uniform weights", {
  # n equal weights: ESS is n, perplexity is n, the largest weight is 1/n.
  p <- rep(1 / 8, 8L)
  d <- .sirWeightDiagnostics(p, nSuccessful = 8L)
  expect_equal(d$ess, 8, tolerance = 1e-12)
  expect_equal(d$essFraction, 1, tolerance = 1e-12)
  expect_equal(d$maxWeight, 1 / 8, tolerance = 1e-12)
  expect_equal(d$perplexity, 8, tolerance = 1e-12)
})

test_that("weight diagnostics are exact for a fully degenerate weight", {
  # All the mass on one candidate: ESS and perplexity are both 1.
  p <- c(1, rep(0, 9L))
  d <- .sirWeightDiagnostics(p, nSuccessful = 10L)
  expect_equal(d$ess, 1, tolerance = 1e-12)
  expect_equal(d$essFraction, 0.1, tolerance = 1e-12)
  expect_equal(d$maxWeight, 1, tolerance = 1e-12)
  expect_equal(d$perplexity, 1, tolerance = 1e-12)
})

test_that("ESS falls between the degenerate and uniform extremes", {
  p <- c(0.7, 0.2, 0.05, 0.05)
  d <- .sirWeightDiagnostics(p, nSuccessful = 4L)
  expect_gt(d$ess, 1)
  expect_lt(d$ess, 4)
  # 1 / sum(p^2), computed by hand.
  expect_equal(d$ess, 1 / (0.7^2 + 0.2^2 + 2 * 0.05^2), tolerance = 1e-12)
  # Perplexity is exp of the Shannon entropy of the weights.
  ent <- -sum(p * log(p))
  expect_equal(d$perplexity, exp(ent), tolerance = 1e-12)
})

test_that("weight diagnostics ignore zero-probability candidates", {
  # Failed evaluations carry probability zero and must not count as support.
  p <- c(rep(1 / 4, 4L), rep(0, 6L))
  d <- .sirWeightDiagnostics(p, nSuccessful = 4L)
  expect_equal(d$ess, 4, tolerance = 1e-12)
  expect_equal(d$nNonNegligible, 4L)
})

test_that("the iteration summary carries the weight diagnostics", {
  skip_on_cran()
  s <- iter1()$iterSummary
  for (nm in c("ess", "essFraction", "maxWeight", "perplexity", "nNonNegligible")) {
    expect_true(nm %in% names(s), info = nm)
  }
  expect_gt(s$ess, 0)
  expect_lte(s$ess, s$nSuccessful)
  expect_gte(s$essFraction, 0)
  expect_lte(s$essFraction, 1)
})

test_that("a degenerate importance sample warns", {
  skip_on_cran()
  fit <- theoFit()
  # A proposal far narrower than the likelihood makes a handful of candidates
  # carry the weight, which is exactly the situation the diagnostics exist to
  # surface.
  expect_warning(
    suppressMessages(sirRunIteration(
      fit,
      mu = .sirProposalMu(fit),
      proposalCov = sirGetProposalCov(fit) * 400,
      nSamples = 30L,
      nResample = 6L,
      iterNum = 1L,
      recenter = FALSE,
      boxcox = FALSE,
      directory = NULL
    )),
    "effective sample size|weight"
  )
})

# S2 -------------------------------------------------------------------------

test_that("the noise band uses the run's own resampler and cap", {
  skip_on_cran()
  obj <- sirObj()
  quant <- seq(0.1, 0.9, by = 0.1)

  # The band must be reproducible given a seed, because it is generated by the
  # same weighted resampler that produced the retained sample.
  set.seed(101)
  a <- .sirDofvNoise(obj, 1L, quant, nReplicate = 50L, capResampling = 1)
  set.seed(101)
  b <- .sirDofvNoise(obj, 1L, quant, nReplicate = 50L, capResampling = 1)
  expect_equal(a, b)

  expect_true(all(a$low <= a$high))
  expect_equal(nrow(a), length(quant))
})

test_that("noise replicates obey the resampling cap", {
  skip_on_cran()
  # The property that distinguishes the real resampler from the sample.int()
  # call this used to use: with limited replacement no candidate may appear
  # more than `cap` times, whereas unlimited replacement lets one candidate
  # take every slot. Checked on sirResample() directly, because that is now
  # what generates the band.
  set.seed(303)
  n <- 6L
  probs <- c(0.5, 0.2, 0.12, 0.1, 0.05, 0.03)
  mat <- matrix(seq_len(n), ncol = 1L, dimnames = list(NULL, "deltaofv"))
  w <- data.frame(prob_resample = probs)

  for (cap in c(1L, 2L, 3L)) {
    drawn <- sirResample(mat, w, m = min(10L, n * cap), capResampling = cap)
    expect_lte(max(table(drawn$selectionOrder)), cap)
  }
})

test_that("the noise band honours capResampling rather than assuming 1", {
  skip_on_cran()
  obj <- sirObj()
  quant <- seq(0.1, 0.9, by = 0.1)

  set.seed(202)
  cap1 <- .sirDofvNoise(obj, 1L, quant, nReplicate = 80L, capResampling = 1)
  set.seed(202)
  cap3 <- .sirDofvNoise(obj, 1L, quant, nReplicate = 80L, capResampling = 3)

  # Limited replacement lets one candidate appear up to `cap` times, which is a
  # different resampler and so a different band. If the cap were ignored these
  # would be identical.
  expect_false(isTRUE(all.equal(cap1$low, cap3$low)))
})

test_that("the convergence plot passes the run's controls to the noise band", {
  skip_on_cran()
  obj <- sirObj()
  # The effective controls are recorded on the result so diagnostics describe
  # the algorithm that actually produced the retained sample.
  expect_false(is.null(attr(obj, "control")))
  expect_no_error(suppressWarnings(plot(obj, type = "convergence", noise = TRUE)))
})
